//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string autores { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> fpublicacion { get; set; }
        public Nullable<int> nejemplares { get; set; }
        public string categoria { get; set; }
    }
}
